name: Task2 - Frontend & Java Backend CI

on:
  push:
    paths:
      - "task2/**"
  pull_request:
    paths:
      - "task2/**"

jobs:
  frontend:
    name: Frontend (Next.js)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"
          cache-dependency-path: task2/package-lock.json

      - name: Install deps
        working-directory: task2
        run: npm ci

      - name: Lint
        working-directory: task2
        run: npm run lint --if-present

      - name: Build
        working-directory: task2
        run: npm run build

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: nextjs-build
          path: |
            task2/.next
            task2/.next/static
          if-no-files-found: warn

  backend-java:
    name: Backend (Java)
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"
          cache: "maven"

      - name: Build & Test
        working-directory: task2/backend-java
        run: mvn -B verify

      - name: Log in to Container Registry
        if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/')
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.REGISTRY }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and (conditionally) push Docker image
        uses: docker/build-push-action@v5
        with:
          context: task2/backend-java
          file: task2/backend-java/Dockerfile
          push: ${{ github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/') }}
          tags: |
            ${{ secrets.REGISTRY }}/${{ github.repository }}-task2-backend:latest
            ${{ secrets.REGISTRY }}/${{ github.repository }}-task2-backend:${{ github.sha }}